# This file was generated by GoReleaser. DO NOT EDIT.
class Tfupdate < Formula
  desc "Update version constraints in your Terraform configurations"
  homepage "https://github.com/minamijoyo/tfupdate"
  version "0.5.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/minamijoyo/tfupdate/releases/download/v0.5.1/tfupdate_0.5.1_darwin_amd64.tar.gz"
    sha256 "9671d62e879f26f27698942d66d64f6413e8dbedeb4b2b8aeb8786014a5ee1db"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/tfupdate/releases/download/v0.5.1/tfupdate_0.5.1_linux_amd64.tar.gz"
      sha256 "081f552d45ff3476d151fd54dabc6cab3021bd556b89389917fbe2e665192fa3"
    end
  end

  def install
    bin.install "tfupdate"
  end

  test do
    system "#{bin}/tfupdate --version"
  end
end
