# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfupdate < Formula
  desc "Update version constraints in your Terraform configurations"
  homepage "https://github.com/minamijoyo/tfupdate"
  version "0.6.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/tfupdate/releases/download/v0.6.3/tfupdate_0.6.3_darwin_amd64.tar.gz"
      sha256 "ea4e0a2fbdf3b2efbf80c7679757bc3030acd43a270c833f1b188b8ff419e563"

      def install
        bin.install "tfupdate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/minamijoyo/tfupdate/releases/download/v0.6.3/tfupdate_0.6.3_darwin_arm64.tar.gz"
      sha256 "481a40428346f36daf120960baeeecf8ba8fbe29943c7c7e5f6f340f3dccafda"

      def install
        bin.install "tfupdate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/tfupdate/releases/download/v0.6.3/tfupdate_0.6.3_linux_amd64.tar.gz"
      sha256 "b4da2e7385247a39cdf5d9c51737ae8887a5cd10969336b4a514ad080ac24ec8"

      def install
        bin.install "tfupdate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/minamijoyo/tfupdate/releases/download/v0.6.3/tfupdate_0.6.3_linux_arm64.tar.gz"
      sha256 "0f19792b1e11cf4ebf5e56e46bf0eebda0c9c0f32af8b8614c8f151b9901bd46"

      def install
        bin.install "tfupdate"
      end
    end
  end

  test do
    system "#{bin}/tfupdate --version"
  end
end
